apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: codelikebasics-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/rate-limit: "100"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - codelikebasics.com
    - www.codelikebasics.com
    secretName: codelikebasics-tls
  rules:
  - host: codelikebasics.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: codelikebasics-service
            port:
              number: 80
  - host: www.codelikebasics.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: codelikebasics-service
            port:
              number: 80
