apiVersion: v1
kind: Service
metadata:
  name: codelikebasics-service
  labels:
    app: codelikebasics
spec:
  type: LoadBalancer
  selector:
    app: codelikebasics
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
  sessionAffinity: None
